[package]
name = "ppk4n-wasm-edition"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "2.2.6"
leb128 = "0.2.5"
rustpython-parser = "0.3.1"

# [profile.release]
# lto = true
# strip = true
