#!/usr/bin/env python3
"""
Yet another script of mine.

Usage: {script} [options] PATH

Arguments:
    PATH - Path to ppkn script to run.

Options:
    -h, --help
        Show this screen and exit.
"""
import sys
from scanner import scan_tokens
from contextlib import suppress
from pathlib import Path


def main(script_name: str, *script_args: str):
    doc = __doc__.format(script=Path(script_name).name)
    args = __import__("docopt").docopt(doc, script_args)
    path = Path(args["PATH"])
    scan_tokens(path.read_text())


if __name__ == "__main__":
    with suppress(KeyboardInterrupt):
        main(sys.argv[0], *sys.argv[1:])
